kind: Service
apiVersion: v1
metadata:
  name: appconnect
spec:
  type: LoadBalancer
  selector:
    app: appconnect
  ports:
  - protocol: TCP
    port: 7600
    targetPort: 7600
  - protocol: TCP
    port: 7800
    targetPort: 7800
  - protocol: TCP
    port: 7843
    targetPort: 7843
  - protocol: TCP
    port: 1414
    targetPort: 1414
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: appconnect
  labels:
    app: appconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appconnect
  template:
    metadata:
      labels:
        app: appconnect
    spec:
      containers:
      - name: appconnect
        image: us.gcr.io/sincere-chariot-260312/ace-dev-mq-dev@sha256:fb00747d9568852165a190192969e5389f9af83b0c1eeb7e58d98b20aa647c0b
        ports:
        - containerPort: 7600
        - containerPort: 7800
        - containerPort: 7843
        - containerPort: 1414
        env:
        - name: LICENSE
          value: "accept"
        - name: MQ_QMGR_NAME
          value: "QMGR"
        - name: ACE_SERVER_NAME
          value: "ACESERVER"
        command: ["echo"]
        args: ["$(LICENSE) $(MQ_QMGR_NAME) $(ACE_SERVER_NAME)"]
