kind: Service
apiVersion: v1
metadata:
  name: appconnect
spec:
  type: LoadBalancer
  selector:
    app: appconnect
  ports:
  - name: admin
    port: 7600
    targetPort: 7600
  - name: adminbus
    port: 7800
    targetPort: 7800
  - name: adminbusseguro
    port: 7843
    targetPort: 7843
  - name: adminmq
    port: 1414
    targetPort: 1414
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: appconnect
  labels:
    app: appconnect
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appconnect
  template:
    metadata:
      labels:
        app: appconnect
    spec:
      containers:
      - name: appconnect
        image: gcr.io/sincere-chariot-260312/davivienda@sha256:e114b64d91eb58a771cf69a3027f49156015ddff97fb94bf52c5d91a486118bb
        ports:
        - containerPort: 7600
          name: xaaa
        - containerPort: 7800
          name: yeee
        - containerPort: 7843
          name: ziii
        - containerPort: 1414
          name: aooo
        env:
        - name: LICENSE
          value: "accept"
        - name: MQ_QMGR_NAME
          value: "QMGR"
        - name: ACE_SERVER_NAME
          value: "ACESERVER"
        #command: ["echo"]
        #args: ["$(LICENSE) $(MQ_QMGR_NAME) $(ACE_SERVER_NAME)"]
